[package]
name = "manifests"
version = "1.2.40"
edition = "2021"


[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
core-utils = { workspace = true }
identified-vec-of = { workspace = true }
hierarchical-deterministic = { workspace = true }
factors = { workspace = true }
addresses = { workspace = true }
metadata = { workspace = true }
transaction-models = { workspace = true }
gateway-models = { workspace = true }
profile = { workspace = true }
profile-account-or-persona = { workspace = true }
profile-supporting-types = { workspace = true }
profile-base-entity = { workspace = true }
account-for-display = { workspace = true }
radix-name-service = { workspace = true }

# === RADIX DEPENDENCIES ===
radix-common = { workspace = true }
radix-engine = { workspace = true }
radix-engine-interface = { workspace = true }
radix-engine-toolkit = { workspace = true }
radix-engine-toolkit-common = { workspace = true }
radix-rust = { workspace = true }
radix-transactions = { workspace = true }
sbor = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
enum-as-inner = { workspace = true }
enum-iterator = { workspace = true }
itertools = { workspace = true }
paste = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
cargo_toml = { workspace = true }
