[package]
name = "build-info"
version = "1.2.30"
edition = "2021"
build = "build.rs"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
assert-json = { workspace = true }
error = { workspace = true }
has-sample-values = { workspace = true }

# === RADIX DEPENDENCIES ===
radix-engine = { workspace = true }
radix-engine-toolkit = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
enum-as-inner = { workspace = true }

[build-dependencies]
cargo_toml = { workspace = true }
