[package]
name = "profile-security-structures"
version = "1.2.42"
edition = "2021"

[dependencies]
# === INTERNAL DEPENDENCIES ===
prelude = { workspace = true }
identified-vec-of = { workspace = true }
hierarchical-deterministic = { workspace = true }
factors = { workspace = true }
has-sample-values = { workspace = true }
addresses = { workspace = true }
cap26-models = { workspace = true }
next-derivation-index-ephemeral = { workspace = true }
network = { workspace = true }
core-collections = { workspace = true }
time-utils = { workspace = true }
short-string = { workspace = true }
core-utils = { workspace = true }
core-misc = { workspace = true }          # decl_bool_type

# === RADIX DEPENDENCIES ===
radix-engine-interface = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
enum-as-inner = { workspace = true }
log = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
