[package]
name = "account-for-display"
version = "1.2.34"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
addresses = { workspace = true }
short-string = { workspace = true }
entity-foundation = { workspace = true }
identified-vec-of = { workspace = true }
network = { workspace = true }
has-sample-values = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
serde = { workspace = true }
