[package]
name = "host-info"
version = "1.2.18"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
assert-json = { workspace = true }
has-sample-values = { workspace = true }
time-utils = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
