[package]
name = "identified-vec-of"
version = "1.2.4"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
assert-json = { workspace = true }
error = { workspace = true }

# === RADIX DEPENDENCIES
# None

# === EXTERNAL DEPENDENCIES
derive_more = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
