[package]
name = "http-client"
version = "1.2.39"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
drivers = { workspace = true }
bytes = { workspace = true }
error = { workspace = true }
core-utils = { workspace = true }

# === RADIX DEPENDENCIES ===

# === EXTERNAL DEPENDENCIES ===
reqwest = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
actix-rt = { workspace = true }
