[package]
name = "hierarchical-deterministic"
version = "1.2.3"
edition = "2021"

[dependencies]
# ==== INTERNAL DEPENDENCIES ====
prelude = { workspace = true }
identified-vec-of = { workspace = true }
ecc = { workspace = true }
hash = { workspace = true }
cap26-models = { workspace = true }
bytes = { workspace = true }
has-sample-values = { workspace = true }
assert-json = { workspace = true }
network = { workspace = true }
numeric = { workspace = true }

# ==== RADIX DEPENDENCIES ====
radix-common = { workspace = true }

# ==== EXTERNAL DEPENDENCIES ====
bip39 = { workspace = true }
derive_more = { workspace = true }
enum-as-inner = { workspace = true }
enum-iterator = { workspace = true }
iota-crypto = { workspace = true }
itertools = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true }
zeroize = { workspace = true }
