[package]
name = "error"
version = "1.2.15"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
# None besides 'prelude'
prelude = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
log = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
derive_more = { workspace = true }
strum = { workspace = true }
