[package]
name = "ecc"
version = "1.2.24"
edition = "2021"

[dependencies]
# ==== INTERNAL DEPENDENCIES ====
prelude = { workspace = true }
has-sample-values = { workspace = true }
error = { workspace = true }
assert-json = { workspace = true }
bytes = { workspace = true }
hash = { workspace = true }
identified-vec-of = { workspace = true }

# ==== RADIX DEPENDENCIES ====
radix-common = { workspace = true }
radix-transactions = { workspace = true }

# ==== EXTERNAL DEPENDENCIES ====
derive_more = { workspace = true }
enum-as-inner = { workspace = true }
hex = { workspace = true }
iota-crypto = { workspace = true }
k256 = { workspace = true }
log = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
zeroize = { workspace = true }
