[package]
name = "sargon-os-derive-public-keys"
version = "1.2.44"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
sargon-os = { path = "../../../system/os/os" }
error = { workspace = true }
key-derivation-traits = { workspace = true }
keys-collector = { workspace = true }
profile = { workspace = true }

# ==== RADIX DEPENDENCIES ====
# None

# ==== EXTERNAL DEPENDENCIES ====
actix-rt = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }
log = { workspace = true }

[dev-dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
drivers = { workspace = true }
interactors = { workspace = true }
clients = { workspace = true }
key-derivation-traits = { workspace = true }
