[package]
name = "core-utils"
version = "1.2.38"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
error = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
iso8601-timestamp = { workspace = true }
log = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
