[package]
name = "cap26-models"
version = "1.2.48"
edition = "2021"

[dependencies]
# ==== INTERNAL DEPENDENCIES ====
prelude = { workspace = true }
has-sample-values = { workspace = true }
error = { workspace = true }
numeric = { workspace = true }
assert-json = { workspace = true }
# bytes = { workspace = true }
# hash = { workspace = true }
# identified-vec-of = { workspace = true }

# ==== RADIX DEPENDENCIES ====
# None

# ==== EXTERNAL DEPENDENCIES ====
enum-as-inner = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true }
serde_repr = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
