[package]
name = "sargon-os-signing"
version = "1.2.45"
edition = "2021"

[features]
mock = ["mockall"]

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
sargon-os = { path = "../../../system/os/os" }
error = { workspace = true }
signatures-collector = { workspace = true }
signing-traits = { workspace = true }
transaction-models = { workspace = true }
profile-security-structures = { workspace = true }
radix-connect-models = { workspace = true }
profile = { workspace = true }
profile-logic = { workspace = true }
manifests = { workspace = true }
profile-supporting-types = { workspace = true }
radix-engine-interface = { workspace = true }

# ==== RADIX DEPENDENCIES ====
# None

# ==== EXTERNAL DEPENDENCIES ====
actix-rt = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
extend = { workspace = true }
mockall = { workspace = true, optional = true }

[dev-dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
drivers = { workspace = true }
interactors = { workspace = true }
clients = { workspace = true }
factor-instances-provider = { workspace = true }
key-derivation-traits = { workspace = true }
mockall = { workspace = true }
