[package]
name = "factor-instances-provider"
version = "1.2.7"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
identified-vec-of = { workspace = true }
assert-json = { workspace = true }
core-utils = { workspace = true }
error = { workspace = true }
factors = { workspace = true }
hierarchical-deterministic = { workspace = true }
keys-collector = { workspace = true }
addresses = { workspace = true }
profile = { workspace = true }
profile-logic = { workspace = true }
clients = { workspace = true }
key-derivation-traits = { workspace = true }
profile-supporting-types = { workspace = true }
next-derivation-index-ephemeral = { workspace = true }

# ==== RADIX DEPENDENCIES ====
# None

# ==== EXTERNAL DEPENDENCIES ====
derive_more = { workspace = true }
futures = { workspace = true }
indexmap = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
actix-rt = { workspace = true }
