[package]
name = "core-collections"
version = "1.2.16"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
has-sample-values = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
indexmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
