[package]
name = "interactors"
version = "1.2.48"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
signing-traits = { workspace = true }
key-derivation-traits = { workspace = true }
transaction-models = { workspace = true }

# ==== RADIX DEPENDENCIES ====
# None

# ==== EXTERNAL DEPENDENCIES ====
async-trait = { workspace = true }
derive_more = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
