[package]
name = "core-misc"
version = "1.2.15"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
assert-json = { workspace = true }
error = { workspace = true }
core-utils = { workspace = true }
has-sample-values = { workspace = true }

# === RADIX DEPENDENCIES ===
radix-common = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
iso8601-timestamp = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
