[package]
name = "profile-persona"
version = "1.2.6"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
short-string = { workspace = true }
hierarchical-deterministic = { workspace = true }
has-sample-values = { workspace = true }
addresses = { workspace = true }
host-info = { workspace = true }
core-misc = { workspace = true }
cap26-models = { workspace = true }
profile-base-entity = { workspace = true }
profile-persona-data = { workspace = true }
profile-security-structures = { workspace = true }


# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
