[package]
name = "entity-foundation"
version = "1.2.40"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
assert-json = { workspace = true }
error = { workspace = true }
has-sample-values = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
itertools = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
