[package]
name = "short-string"
version = "1.2.11"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
identified-vec-of = { workspace = true }
assert-json = { workspace = true }
core-utils = { workspace = true }
has-sample-values = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
arraystring = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
serde_json = { workspace = true }
