[package]
name = "sargon-os-security-center"
version = "1.2.34"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
sargon-os = { path = "../../../system/os/os" }
drivers = { workspace = true }
has-sample-values = { workspace = true }
error = { workspace = true }
security-center = { workspace = true }

# ==== RADIX DEPENDENCIES ====
# None

# ==== EXTERNAL DEPENDENCIES ====
actix-rt = { workspace = true }
derive_more = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
