[package]
name = "factors"
version = "1.2.39"
edition = "2021"

[dependencies]
# ==== INTERNAL DEPENDENCIES ====
prelude = { workspace = true }
identified-vec-of = { workspace = true }
bytes = { workspace = true }
hierarchical-deterministic = { workspace = true }
encryption = { workspace = true }
hash = { workspace = true }
ecc = { workspace = true }
cap26-models = { workspace = true }
numeric = { workspace = true }
network = { workspace = true }
time-utils = { workspace = true }
short-string = { workspace = true }
host-info = { workspace = true }
core-misc = { workspace = true }
core-utils = { workspace = true }
core-collections = { workspace = true }

# ==== RADIX DEPENDENCIES ====
radix-common = { workspace = true }
radix-engine-interface = { workspace = true }

# ==== EXTERNAL DEPENDENCIES ====
derive_more = { workspace = true }
enum-as-inner = { workspace = true }
enum-iterator = { workspace = true }
hkdf = { workspace = true }
iota-crypto = { workspace = true }
indexmap = { workspace = true }
k256 = { workspace = true }
once_cell = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
zeroize = { workspace = true }

[build-dependencies]
prelude = { workspace = true }
