[package]
name = "gateway-client-and-api"
version = "1.2.41"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
assert-json = { workspace = true }
core-utils = { workspace = true }
metadata = { workspace = true }
addresses = { workspace = true }
drivers = { workspace = true }
http-client = { workspace = true }
gateway-models = { workspace = true }
transaction-models = { workspace = true }
profile-gateway = { workspace = true }
profile-base-entity = { workspace = true }

# === RADIX DEPENDENCIES ===
radix-common = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
actix-rt = { workspace = true }
