[package]
name = "next-derivation-index-ephemeral"
version = "1.2.5"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
identified-vec-of = { workspace = true }
assert-json = { workspace = true }
error = { workspace = true }
hierarchical-deterministic = { workspace = true }
has-sample-values = { workspace = true }
factors = { workspace = true }
cap26-models = { workspace = true }
addresses = { workspace = true }
network = { workspace = true }

# === RADIX DEPENDENCIES
#None

# === EXTERNAL DEPENDENCIES
enum-iterator = { workspace = true }
derive_more = { workspace = true }
indexmap = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
serde_json = { workspace = true }
