[package]
name = "addresses"
version = "1.2.48"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
identified-vec-of = { workspace = true }
factors = { workspace = true }
hierarchical-deterministic = { workspace = true }
hash = { workspace = true }
ecc = { workspace = true }
cap26-models = { workspace = true }
bytes = { workspace = true }
network = { workspace = true }
has-sample-values = { workspace = true }
assert-json = { workspace = true }
core-utils = { workspace = true }

# ==== RADIX DEPENDENCIES ====
radix-common = { workspace = true }
radix-engine = { workspace = true }
radix-engine-interface = { workspace = true }
radix-engine-toolkit = { workspace = true }
radix-rust = { workspace = true }

# ==== EXTERNAL DEPENDENCIES ====
derive_more = { workspace = true }
enum-as-inner = { workspace = true }
enum-iterator = { workspace = true }
log = { workspace = true }
paste = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
