[package]
name = "clients"
version = "1.2.38"
edition = "2021"


[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
core-collections = { workspace = true }
profile = { workspace = true }
factors-supporting-types = { workspace = true }
profile-supporting-types = { workspace = true }
drivers = { workspace = true, features = ["mock"] }
http-client = { workspace = true }
gateway-client-and-api = { workspace = true }
hierarchical-deterministic = { workspace = true }
signing-traits = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
async-trait = { workspace = true }
derive_more = { workspace = true }
enum-as-inner = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
extend = { workspace = true }

[dev-dependencies]
actix-rt = { workspace = true }
mockall = { workspace = true }
