[package]
name = "keys-collector"
version = "1.2.28"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
has-sample-values = { workspace = true }
factors = { workspace = true }
numeric = { workspace = true }
hierarchical-deterministic = { workspace = true }
addresses = { workspace = true }
cap26-models = { workspace = true }
network = { workspace = true }
error = { workspace = true }
core-misc = { workspace = true }                  # HiddenConstructor
core-collections = { workspace = true }
factors-supporting-types = { workspace = true }
key-derivation-traits = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
actix-rt = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }
itertools = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true }
