[package]
name = "sub-systems"
version = "1.2.21"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
drivers = { workspace = true } # Actually need only logging driver.. TODO split out?

# ==== RADIX DEPENDENCIES ====
# None

# ==== EXTERNAL DEPENDENCIES ====
derive_more = { workspace = true }
enum-iterator = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
