[package]
name = "radix-connect"
version = "1.2.1"
edition = "2021"


[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
assert-json = { workspace = true }
core-utils = { workspace = true }
addresses = { workspace = true }
identified-vec-of = { workspace = true }
ecc = { workspace = true }
hash = { workspace = true }
bytes = { workspace = true }
profile-persona-data = { workspace = true }
core-misc = { workspace = true }
http-client = { workspace = true }
drivers = { workspace = true }
encryption = { workspace = true }
transaction-foundation = { workspace = true }
transaction-models = { workspace = true }
entity-foundation = { workspace = true }
short-string = { workspace = true }
has-sample-values = { workspace = true }
radix-connect-models = { workspace = true }
profile-security-structures = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
actix-rt = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
derive_more = { workspace = true }
hex = { workspace = true }
paste = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
serde_json = { workspace = true }
