[package]
name = "factors-supporting-types"
version = "1.2.4"
edition = "2021"

[dependencies]
# ==== INTERNAL DEPENDENCIES ====
prelude = { workspace = true }
identified-vec-of = { workspace = true }
hierarchical-deterministic = { workspace = true }
factors = { workspace = true }
error = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
async-trait = { workspace = true }
